"""配置模块"""

from .settings import (
    PROJECT_ROOT,
    SCREENSHOT_DIR,
    DEFAULT_API_TIMEOUT,
    DEFAULT_MAX_ITERATIONS,
    DEFAULT_SCREENSHOT_DELAY_MS,
    MAX_SCREENSHOTS_IN_HISTORY,
)

__all__ = [
    "PROJECT_ROOT",
    "SCREENSHOT_DIR",
    "DEFAULT_API_TIMEOUT",
    "DEFAULT_MAX_ITERATIONS",
    "DEFAULT_SCREENSHOT_DELAY_MS",
    "MAX_SCREENSHOTS_IN_HISTORY",
]
